### ISSUE TITLE
If there is a value on a quote make sure to push an eventValue key/value pair

### ISSUE THREAD

**Issue by jamesscaggs** [JonatanAcosta/AeroAccess#2]
https://github.com/JonatanAcosta/AeroAccess/blob/e24cd61ecc915b5484621639a5acbf660f451e06/dataLayer#L44

**Comment by JonatanAcosta** [comment]
"event": "quoteComplete" // fires when user successfully completes all steps to get a quote RFQ process
	"quoteAmount" "quote amount" // replace this string with a var that displays the amount quoted in final process of quote checkout
